language: c
compiler:
  - clang
sudo: false
addons:
  apt:
    packages:
    - make
    - autoconf
    - build-essential
    - libcurl4-openssl-dev
    - libtool
    - libjansson-dev
before_install:
  - pip install --user cpp-coveralls
  - cd src
script:
  - make
  - make check
