language: cpp
compiler:
  - clang
sudo: false
addons:
  apt:
    packages:
    - make
    - autoconf
    - build-essential
    - libcurl4-openssl-dev
    - libtool
    - libjansson-dev
    - check
    - llvm-3.0
    - splint
before_install:
  - pip install --user cpp-coveralls
  - cd src
script:
  - make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

