language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjansson-dev libcurl4-openssl-dev libtool
  - pip install --user cpp-coveralls
  - cd src
script:
  - make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

