#! /bin/bash
# Written by Furey.
# With additions from Tony.
# With changes from Kahn.

# Load .env variables
if [ -e .env ]; then
  export $(cat .env | grep -v ^\# | xargs)
fi

# Set the port number.
PORT=1234

if [ -z $1 ]; then
  PORT="$1"
fi

# Change to area directory.
cd ./area

# Set limits.
ulimit -s 1024

if [ -e shutdown.txt ]; then
  rm -f shutdown.txt
fi

ulimit -c unlimited

while true; do
  # If you want to have logs in a different directory,
  # change the 'set logfile' line to reflect the directory name.
  INDEX=1000

  while true; do
    logfile="../log/$INDEX.log"

    if [ ! -e $logfile ]; then
      break
    fi

    INDEX=$((INDEX+1))
  done

  # Run envy.
  if [ -e shutdown.txt ]; then
     rm -f shutdown.txt
  fi

  ../bin/envy $PORT > $logfile

  if [ -e core ]; then
    mv core ../bin/$INDEX.core
  fi

  # Restart, giving old connections a chance to die.
  if [ -e shutdown.txt ]; then
    rm -f shutdown.txt
    exit 0
  fi

  sleep 5
done
