include Makefile

default: $(MAIN_OBJ) $(OBJS)
	@echo "[1;35mBuilding the [1;32mOASIS[0;37m"
	rm -f envy
	$(CC) $(L_FLAGS) -o envy $(MAIN_OBJ) $(OBJS) $(PKG_CFG)
	@echo "Done."

clean:
	rm -f *.o
	rm -f envy
	make default -f Makefile.envy

%.o: %.c
	$(CC) $(C_FLAGS) $< -o $@
