include Makefile

TEST_C_FLAGS  = $(C_FLAGS) -fprofile-arcs -ftest-coverage
TEST_L_FLAGS  = $(L_FLAGS) -lgcov -coverage
TEST_OBJS 		= $(OBJS) tests/main.o tests/mocks.o tests/test.act_info.o \
								tests/test.act_wiz.o

default: $(TEST_OBJS)
	@echo "[1;35mBuilding the [1;32mTests[0;37m"
	rm -rf tests/test.envy
	$(CC) $(TEST_L_FLAGS) -o tests/test.envy $(TEST_OBJS) $(PKG_CFG) -lcunit
	@echo "Done."

clean:
	rm -f *.o
	rm -f tests/*.o
	rm -f tests/test.envy
	make default -f Makefile.test

%.o: %.c
	$(CC) $(TEST_C_FLAGS) $< -o $@

tests/%.o: tests/%.c
	$(CC) $(TEST_C_FLAGS) $< -o $@
